### ISSUE TITLE
Different files depending on operating system?

### ISSUE THREAD

**Issue by superpoincare** [majodev/google-webfonts-helper#10]
I think Google Fonts also sends different files depending on the operating system. So Chrome 46 in Windows will receive a different woff2 file than Chrome 46 in OS X. 

Do you have a method to deal with this?

**Comment by davelab6** [comment]
That difference is the hinting

**Comment by davelab6** [comment]
To deal with this means increasing the complexity of self hosting a lot: it requires people to run a web server that can detect the user-agent string of visitors, look up which fonts are best appropriate for that user-agent, and return a CSS file that points to those particular fonts. 

To be legal, it also requires gathering RFN permission for all the OFL fonts that have RFNs (which is boring admin work that sucks.)

**Comment by superpoincare** [comment]
Yeah I would have imagined the server detecting the user agent and then making a css file based on that. 

So I assume your program does some normalization between different fonts, or do you pick a Windows version of the font files? 

How much is the perceived difference in how the fonts look between google-hosted and self-hosted?

**Comment by davelab6** [comment]
I don't have a program, I'm part of the gf team :) The differences can't be perceived visually, the difference is in the filesize - latency.

**Comment by superpoincare** [comment]
Oops. I confused you with the google-fonts-helper author. 

My question was that if I use google-fonts-helper, which woff2 does it provide in the kit available for download? Windows or Mac? Or some different woff2?

Also, I noticed a slight bump on second load when I tried this, even though the cache headers seem fine and unlike directly loading it from Google Fonts.

**Comment by majodev** [comment]
Hi, 

Currently Windows UAs are used for fetching the fonts, also see #5 were this was previously discussed.

The exact user-agents that are currently used can be seen [here](https://github.com/majodev/google-webfonts-helper/blob/master/server/logic/conf.js#L2).

**Comment by superpoincare** [comment]
Very helpful @majodev. Thanks also to @davelab6
