### ISSUE TITLE
API Error (503) Yanone Kaffeesatz sans-serif

### ISSUE THREAD

**Issue by wschern** [majodev/google-webfonts-helper#100]
Hello,
I'm getting an API Error (503) at requesting the Yanone Kaffeesatz sans-serif Font:

> API Error (503)
REQUEST CONFIG: {
  "method": "GET",
  "transformRequest": [
    null
  ],
  "transformResponse": [
    null
  ],
  "url": "/api/fonts/yanone-kaffeesatz?subsets=latin",
  "headers": {
    "Accept": "application/json, text/plain, */*"
  }
}
REQUEST HEADERS:

**Comment by leifj** [comment]
I'm seeing this also with other fonts.

**Comment by scrobbleme** [comment]
Duplicate of #99
