### ISSUE TITLE
'No Sans KR' has no .ttf

### ISSUE THREAD

**Issue by Dev-Jeromebaek** [majodev/google-webfonts-helper#102]
https://google-webfonts-helper.herokuapp.com/fonts/noto-sans-kr?subsets=korean,latin

I'd like to use this link to provide a font with Bset Support.
But, The .ttf file is missing from the extrusion file.
It looks like we need to check.

**Comment by sunali1** [comment]
Same issue as above https://google-webfonts-helper.herokuapp.com/fonts/noto-sans-kr?subsets=korean
.ttf format missing
