### ISSUE TITLE
Please add Futura PT fonts in your site

### ISSUE THREAD

**Issue by rmuhammadaziz** [majodev/google-webfonts-helper#126]
Futura PT fonts are very important for me

**Comment by webuxr** [comment]
I would love to see Futura PT available on Google Fonts however, it's an Adobe-based webfont (from Paratype):
https://fonts.adobe.com/fonts/futura-pt

If you have an Adobe CS subscription, you can load Futura PT in what Adobe calls a "Web Project". More here: https://helpx.adobe.com/fonts/using/add-fonts-website.html

Cheers!
_rs

**Comment by rmuhammadaziz** [comment]
ok thanks
