### ISSUE TITLE
Service down - usage with @beyonk/google-fonts-webpack-plugin

### ISSUE THREAD

**Issue by FreaKzero** [majodev/google-webfonts-helper#131]
Service is currently unavailable which is pretty bad for webpack builds which use google-fonts-webpack-plugin since the builds will fail silently.

**Comment by filipac** [comment]
yeah, i have the same error. webpack fails to build and breaks build

**Comment by zubairhixol** [comment]
Service down from last three to four hours...

**Comment by filipac** [comment]
Heroku had some incidents, maybe this is related to that?

**Comment by jacobg** [comment]
Linked issues:
https://github.com/majodev/google-webfonts-helper/issues/81
https://github.com/gabiseabra/google-fonts-webpack-plugin/issues/34
https://github.com/beyonk-adventures/google-fonts-webpack-plugin/issues/19

**Comment by mutdmour** [comment]
Created temporary service here to unblock builds
https://n8n-google-fonts-helper.herokuapp.com/api/fonts

Can be used like this:
```
			new GoogleFontsPlugin({
				apiUrl: 'https://n8n-google-fonts-helper.herokuapp.com/api/fonts',
                                ...
			}),
```

**Comment by FreaKzero** [comment]
@mutdmour 
you are a hero!
Thank you so much <3

**Comment by jacobg** [comment]
I switched to using fontsource instead instead (https://fontsource.org/).

It's easy to set up, and avoids remote dependencies other than npm when installing. All that's necessary is:
1) package.json dev dependency - `"@fontsource/open-sans": "^4.5.0"`
2) main.js `import "@fontsource/open-sans/latin-400.css"`
3) css -
```
body {
    font-family: 'Open Sans', sans-serif;
}
```

**Comment by weinde** [comment]
this is still going on... any idea when this will be resolved?

**Comment by Dan0sz** [comment]
> 
> 
> Created temporary service here to unblock builds
> https://n8n-google-fonts-helper.herokuapp.com/api/fonts
> 
> Can be used like this:
> 
> ```
> 			new GoogleFontsPlugin({
> 				apiUrl: 'https://n8n-google-fonts-helper.herokuapp.com/api/fonts',
>                                 ...
> 			}),
> ```

Noob question here, would you like to provide instructions on how I can setup my own mirror of this, too? This has been happening a lot lately, and I'd like to provide a permanent mirror if possible.

**Comment by mutdmour** [comment]
@Dan0sz great idea as I don't plan to support this temporary service forever.. At least until this original service goes back up or https://github.com/n8n-io/n8n migrates over to fontsource.. (I don't have a timeline for this yet, but I will give heads up in this thread and give some time before deprecating, maybe even do a scream test)

I created a fork here and fixed build issues until it was working on heroku with the latest node version
https://github.com/mutdmour/google-webfonts-helper

To deploy this service with Heroku:
1. Fork my fork
2. login/signup with heroku
2. Create new app.. Give it whatever name, and pick your region
3. Once created, under Deploy tab, click on Github as Deployment method
4. Connect to your github account if not already connected
5. Search for your repo and click connect
<img width="752" alt="Screen Shot 2021-09-20 at 11 50 52 AM" src="https://user-images.githubusercontent.com/4711238/133983887-84ca6c2c-f383-4fdd-861b-551c3f41cd21.png">

6. Under manual deploy, click on deploy branch
<img width="1054" alt="Screen Shot 2021-09-20 at 11 45 27 AM" src="https://user-images.githubusercontent.com/4711238/133983285-830c0606-4d2a-405f-b3cd-e341635be224.png">
7. Once deployed, go to https://{{YOUR_APP_NAME}}.herokuapp.com/api/fonts and check you get valid response
8. To minimize interruptions, I would recommend upgrading to a paid dyno

**Comment by c33s** [comment]
are there docs about how to setup this on a basic linux machine (no heroku)?

**Comment by sephentos** [comment]
Glad it came back online...

**Comment by mutdmour** [comment]
With [n8n switching to fontsource](https://github.com/n8n-io/n8n/pull/2220) and the original service back up, I am going to end support for the mirror service (https://n8n-google-fonts-helper.herokuapp.com/api/fonts)..

If you are using this, you have until **October 4th** to make the switch...

**Comment by DecliningLotus** [comment]
> Created temporary service here to unblock builds
> https://n8n-google-fonts-helper.herokuapp.com/api/fonts

I’ve been working on replacing this repo entirely with Fontsource. That includes serving an API for external application (with more plans on improving this service).

Do check out: https://fontsource.org/docs/api/introduction

**Comment by Dan0sz** [comment]
> If you are using this, you have until **October 4th** to make the switch...

I setup my own. Thanks a lot for the help!

I'll also look into migrating to FontSource. The only thing is that I have some users that require access to TTF, EOT files, etc. I guess I should just give them a heads up, that they should update their platforms :)

**Comment by majodev** [comment]
dup https://github.com/majodev/google-webfonts-helper/issues/151#issuecomment-1240398538
