### ISSUE TITLE
"Raleway" font download error

### ISSUE THREAD

**Issue by dbfischer** [majodev/google-webfonts-helper#138]
Hi,

if I try to download font "Raleway" from
https://google-webfonts-helper.herokuapp.com
by pressing the button, an error page occurs:
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command.

Other fonts like "Roboto" work fine.

Can you please fix this issue?

Best regards
Dirk

**Comment by majodev** [comment]
cannot reproduce anymore, looks working within [v1.1.0](https://github.com/majodev/google-webfonts-helper/releases/tag/v1.1.0).
