### ISSUE TITLE
Roboto with all subsets and subvariants fails

### ISSUE THREAD

**Issue by Delicious-Bacon** [majodev/google-webfonts-helper#139]
I wanted to download Roboto typeface with all of its subsets and subvariants.
[google-webfonts-helper](https://google-webfonts-helper.herokuapp.com/fonts/roboto?subsets=cyrillic,cyrillic-ext,greek,greek-ext,latin,latin-ext,vietnamese)

Clicking the download button leads to an application error:
```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail
```

**Comment by Delicious-Bacon** [comment]
It looks like the `vietnamese` charset is the culprit.

**Comment by majodev** [comment]
cannot reproduce anymore, look working.
