### ISSUE TITLE
font-display: swap

### ISSUE THREAD

**Issue by revilodesign** [majodev/google-webfonts-helper#142]
Hey, 

I love your site and use it often for my projects <3

I have 2-3 wishes

1. font-display: swap;

Can you add this by default? Google pagespeed always grumbles when it's missing

2. font-family: 'XYZ', sans-serif;

Can you still add the parameter? With some fonts you have to go to Google Webfonts. This step would be superfluous

3. customize folder prefix

Is it possible that you work with cookies and show the custom folder path that was entered last :)

As I said - I love your tool. I just noticed this while working with it. That would certainly save me and everyone else 3 steps. 

Cheers

**Comment by Zodiac1978** [comment]
`font-display: swap;` is already reported in #135

**Comment by majodev** [comment]
Fixed in [v1.1.0](https://github.com/majodev/google-webfonts-helper/releases/tag/v1.1.0).
