### ISSUE TITLE
Remove surveillance by Google Analytics

### ISSUE THREAD

**Issue by Shamar** [majodev/google-webfonts-helper#148]
As previously requested by @resynth1943 in #114 there are several open source alternatives if you need statistics.

Instead using Google Analytics in https://google-webfonts-helper.herokuapp.com/fonts informs Google about people using your service to get rid of their lock-in: such information has a huge value for them to enable further manipulations of such people.

**Comment by majodev** [comment]
Removed.

**Comment by gitressa** [comment]
Thanks @majodev!
