### ISSUE TITLE
Font zips downloaded via API don't match CSS

### ISSUE THREAD

**Issue by monsterlane** [majodev/google-webfonts-helper#15]
The CSS listed in the web UI doesn't match the font file names when downloading via the API. Fonts with the Cyrillic subset seem to be effected the most.

Example: Seymour One
CSS: seymour-one-v4-latin-ext_latin_cyrillic-regular.eot
File: seymour-one-v4-cyrillic_latin-ext_latin-regular.eot

**Comment by majodev** [comment]
Hm, sorry cannot reproduce this currently, can you provide the specific steps how this actually occured?

https://google-webfonts-helper.herokuapp.com/fonts/seymour-one?subsets=cyrillic,latin,latin-ext

![bildschirmfoto 2016-04-01 um 21 24 29](https://cloud.githubusercontent.com/assets/2149883/14217762/4b4cbd52-f850-11e5-8af0-0b32a56d028d.png)

**Comment by monsterlane** [comment]
Hmm I found the commit where I fixed them but I tried 4-5 and they seem to come out correctly now. If I see it again I'll report it with a better test case thanks!
