### ISSUE TITLE
google-webfonts-helper herokuapp is down

### ISSUE THREAD

**Issue by howdytom** [majodev/google-webfonts-helper#151]
Hi there,

What happened to the Self-Host Google Fonts site? google-webfonts-helper.herokuapp.com is down. There is a Application error showing up. The Self-Host Google Fonts was a really convenient way to grab all webfonts file at once. I really appreciate the hard work you have spent into it!

**Comment by dakur** [comment]
That's recurring issue and will be forever as the service is hosted by an individual for free and has no guarantee for stability. You can:
- switch to [fontsource](https://github.com/majodev/google-webfonts-helper/issues/131#issuecomment-921829647)
- make [your own fork](https://github.com/majodev/google-webfonts-helper/issues/131#issuecomment-922778389)
- wait until it's up again

**Comment by howdytom** [comment]
@majodev Thank you for the quick fix. [google-webfonts-helper.herokuapp.com](url) is back online.

**Comment by majodev** [comment]
JFYI, it fixed itself over night (GMT) - it was actually a problem with the upstream Google fonts API suddenly missing certain font variants (leading to internal server errors).

Anyways, as @dakur said, this service currently runs on Heroku's free tier (which will be [shut down at the end of November](https://devcenter.heroku.com/articles/free-dyno-hours)) and is currently quite sensitive to the high load it received over the last weeks.

Thus, expect more downtime in the upcoming weeks, I'm going to migrate the whole thing to my private cluster. As this is free, don't expect 99.x% uptime - there is no SLA.

**Comment by sephentos** [comment]
> Thus, expect more downtime in the upcoming weeks, I'm going to migrate the whole thing to my private cluster. As this is free, don't expect 99.x% uptime - there is no SLA.

Thanks so much! Highly appreciated.
