### ISSUE TITLE
heroku is turned off

### ISSUE THREAD

**Issue by umutcandev** [majodev/google-webfonts-helper#154]
We can't access the site because heroku is shut down, can you help?

**Comment by majodev** [comment]
If this is a site reliability related issue (downtime), please see: https://github.com/majodev/google-webfonts-helper/issues/151#issuecomment-1240398538

If you're simply unable to access any Heroku services, I'm afraid there is nothing I can do about that.

**Comment by umutcandev** [comment]
Heroku has announced that it will remove all its free packages, so it may have been affected.

**Comment by majodev** [comment]
As said, the service is currently operational, regarding Heroku: 

> Starting **November 28, 2022**, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® plans will no longer be available. [source](https://devcenter.heroku.com/articles/free-dyno-hours)
