### ISSUE TITLE
Application Error, page does not load at all

### ISSUE THREAD

**Issue by martispyc** [majodev/google-webfonts-helper#155]
When I try to visit [link](https://google-webfonts-helper.herokuapp.com/ ), it says that there is an Application Error.

![image](https://user-images.githubusercontent.com/78826178/193853762-0121decb-deba-4735-8793-b7ed92925c5d.png)

**Comment by Guenni1975** [comment]
Same problem here, page does not load.

Also I read that there will be no more free Heroku Dynos from November 28. Hope the app will still be online. If a paid account would be necessary here, it might also be interesting to have a kind of donation button in the app.

**Comment by cxlxin** [comment]
Same here, page is down.
+1 for donation option.

**Comment by majodev** [comment]
Hi, looks like it stabilized again.
Typically I see these problems if the upstream google fonts API has issues. Also see https://github.com/majodev/google-webfonts-helper/issues/151.

**Comment by majodev** [comment]
Closed as moved off from Heroku now.
