### ISSUE TITLE
Future of project: Will the hosted version remain on Heroku?

### ISSUE THREAD

**Issue by candideu** [majodev/google-webfonts-helper#160]
Hello! Does the hosted version of this app use Heroku's free plan? 

If so, it may have to be moved to another host or apply to their open source program, since Heroku is phasing out its free plans: https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

**Comment by majodev** [comment]
[https://github.com/majodev/google-webfonts-helper/issues/151 dup](https://github.com/majodev/google-webfonts-helper/issues/151#issuecomment-1240398538)

Will announce when ready, there is still some time left until 28th Nov.

**Comment by majodev** [comment]
done: https://gwfh.mranftl.com

**Comment by candideu** [comment]
> done: https://gwfh.mranftl.com

Sweet! What are you using to host this instance?
