### ISSUE TITLE
Nunito (not Nunito Sans)

### ISSUE THREAD

**Issue by volker001** [majodev/google-webfonts-helper#171]
The familie name is: "Nunito ExtraLight". This is wrong. It should be "Nunito".

In fontforge i get some warnings:

The following tables in the font were ignored by FontForge 
Ignore 'STAT' table of style attributes
Glyph bounding box exceeds font bounding box for GID 14 
Consecutive errors are not reported. 
In GID 28 the metric (1316) is greater than the specified maximum value ( 1311) 
Consecutive errors are not reported.

**Comment by majodev** [comment]
This service does **not** generate its own font files / metadata, but rather cache/pack/reuse information from the Google Fonts API and its supporting services (CSS is fetched via a fixed user agent, font files from Googles' CDN).

Furthermore, I'm unsure where you are seeing `Nunito ExtraLight`, see [Nunito](https://gwfh.mranftl.com/fonts/nunito?subsets=latin).

<img width="1167" alt="Bildschirm­foto 2023-04-02 um 16 05 18" src="https://user-images.githubusercontent.com/2149883/229357969-00b15efa-cb9e-4438-8281-d7d5d623a9a7.png">
