### ISSUE TITLE
Option to choose styles

### ISSUE THREAD

**Issue by philfreo** [majodev/google-webfonts-helper#2]
Would be cool if there were checkboxes for choosing which font weights / styles you want included, and then the generated CSS / .zip would only include those.

**Comment by majodev** [comment]
To finally finish this: Now only fonts are cached, generated archive is piped directly to response and only includes needed files (based on your previous selection - e.g. only the formats `woff` and `woff2` for the styles `regular` and `300` with the charsets `latin` and `latin-ext`).

Hopefully the free Heroku instance can handle the load, I'll keep an eye on it. Happy local-hosting!
