### ISSUE TITLE
The service seems to be down.

### ISSUE THREAD

**Issue by wmatyjewicz** [majodev/google-webfonts-helper#20]
I am getting an "Application Error" response from the service, both in the browser and through the API.

**Comment by majodev** [comment]
Hi, looks like we are no longer able to request woff2 from the google servers through the specified User-Agent, thus crashing the application. Will look into this tonight.

**Comment by titopinto** [comment]
Hi, I'm facing the same issue.
Please let us know when you fix the issue.

**Comment by majodev** [comment]
up again. fixed.

**Comment by wmatyjewicz** [comment]
Great. Thank you for fixing it quickly.
