### ISSUE TITLE
seem woff2 download has no effect

### ISSUE THREAD

**Issue by noman798** [majodev/google-webfonts-helper#21]
the woff2 font download has not font effect

**Comment by majodev** [comment]
? Please provide a clear description for your encountered error + instructions to reproduce it.

**Comment by TechInterMezzo** [comment]
I've used the tool a couple of days ago, but today there seems to be a problem with some woff2 files. 
An example is the Oswald font. The file "oswald-v10-latin-300.woff2" is now 4kb smaller (~15kb => ~11kb) and the browser can't render it anymore.

I can't tell, if it's the fault of the tool or Google.

**Comment by majodev** [comment]
There seems to a issue with the new set UserAgent here - https://github.com/majodev/google-webfonts-helper/blob/master/server/logic/conf.js#L5 - I'm not totally sure what the most compatible way to get the woff2 format currently. I've recently updated it, as the old specified UserAgent no longer returned anything...

**Comment by TechInterMezzo** [comment]
Google seems to deliver latin and latin-ext, even if latin-ext is not requested.

```
/* latin-ext */
@font-face {
  font-family: 'Oswald';
  font-style: normal;
  font-weight: 300;
  src: local('Oswald Light'), local('Oswald-Light'), url(https://fonts.gstatic.com/s/oswald/v10/l1cOQ90roY9yC7voEhngDBJtnKITppOI_IvcXXDNrsc.woff2) format('woff2');
  unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Oswald';
  font-style: normal;
  font-weight: 300;
  src: local('Oswald Light'), local('Oswald-Light'), url(https://fonts.gstatic.com/s/oswald/v10/HqHm7BVC_nzzTui2lzQTDVtXRa8TVwTICgirnJhmVJw.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
```

Maybe your tool only fetches the first (and wrong) entry, because it expects only latin?

**Comment by majodev** [comment]
@TechInterMezzo perfect - big THX for the heads up! 

unicode-range parsing (and splitting up woff2 files) is not yet supported by the utility. This must have been the problem. Exchange the UserAgent that fetches these woff2 css files from google to an older Firefox Browser (which supports woff2, but not unicode-range).
