### ISSUE TITLE
Source Sans Pro not working in chrome

### ISSUE THREAD

**Issue by sandip8600** [majodev/google-webfonts-helper#22]
I recently downloaded Source Sans Pro font and and copied the css generated. The fonts worked on internet explorer 11 but not on chrome( Version 50.0.2661.94 ). 
Is my version of chrome not supported. Is there something I am missing ?

**Comment by majodev** [comment]
duplicate of #4

**Comment by sandip8600** [comment]
I have solved the issue by downloading 'source sans pro' font from adobe-fonts/source-sans-pro repository https://github.com/adobe-fonts/source-sans-pro 
This repository has all font file along with their css.
