### ISSUE TITLE
Github stars request blocked

### ISSUE THREAD

**Issue by Crysinyan** [majodev/google-webfonts-helper#24]
For whatever reason the github stars frame gets requested over http and gets blocked.
Even though on further inspection the source of the iframe is:
`https://ghbtns.com/github-btn.html?user=majodev&repo=google-webfonts-helper&type=watch&count=true&size=large`

Reproduced in:
Chrome 50.0.2661.94 m
Opera 37.0

**Comment by majodev** [comment]
@Crysinyan I think the former https url actually redirected to http (must have been changed this week), thus this insecure content was blocked). Should work now. Big THX to you for opening an issue for that!
