### ISSUE TITLE
Can Material Icons be included?

### ISSUE THREAD

**Issue by Lopton** [majodev/google-webfonts-helper#30]
Google hosts the Material Icon font collection under google fonts, but it is not listed on the main page. Adding it to this tool may help other people out. 

Link is here:
https://fonts.googleapis.com/icon?family=Material+Icons

more information here:
http://google.github.io/material-design-icons/

**Comment by Lopton** [comment]
never mind this probably is not need since I just saw the Git Hub for them... just go ahead and close this issue.

**Comment by muzuiget** [comment]
+1, Althoughh we can bower install the zip file in repo Release page, but the file som big (60M), we only need the subfolder which only has css and font files.

**Comment by smares** [comment]
Is adding support for Material Icons something you can reconsider? I am using [google-fonts-webpack-plugin](https://github.com/gabiseabra/google-fonts-webpack-plugin) to pull the fonts at compile stage and would like to be able to also specify the Material Icons font. :)
