### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ondrek** [majodev/google-webfonts-helper#33]
No issue, just a simple **thanks**, man! This project saves me seriously like a few hours a week. 

Maybe just buy some own domain, 
because googling "heroku google font download" every time is terrible :-) 

Thanks!

**Comment by ohmybside** [comment]
thx @majodev

**Comment by bagau** [comment]
Big thanks @majodev

**Comment by majodev** [comment]
You are welcome!
