### ISSUE TITLE
ttf missing in download?

### ISSUE THREAD

**Issue by remcokalf** [majodev/google-webfonts-helper#34]
Maybe I am missing something, but when I download the fonts, the ttf files are missing. A few weeks ago when I used the app, it included ttf.

**Comment by PedroMordeP** [comment]
I notice this too yesterday.

For example the Oswald font on the css code is referenced the ttf but when downloading the zip the file is missing

https://google-webfonts-helper.herokuapp.com/fonts/oswald?subsets=latin

**Comment by titopinto** [comment]
Hi,

I'm using your api frequently and you have an awesome service, 
In the last days I'm experience the same issue, the .zip file comes without .ttf

Regards

**Comment by ondrek** [comment]
+1 — missing ttf

**Comment by remcokalf** [comment]
Until this get fixed, you can download the files, including ttf here:

http://nikoskip.me/gfonts.php

I just tested, all types download fine if you use the url like so;
http://fonts.googleapis.com/css?family=Cabin:500,700,500italic,700italic

**Comment by ondrek** [comment]
@remcokalf: Nope. Ain't working for me — TTF is downloaded just for one size (800) for url `fonts.googleapis.com/css?family=Martel+Sans:200,300,400,600,700,800,900&subset=latin-ext`.

**Comment by MikeBull94** [comment]
@ondrek You can download the TTF files one-by-one using the tool linked by @remcokalf and specifying just one variant at a time.

**Comment by TheBogueRat** [comment]
Missing TTF in download today in Roboto, Poppins, and Open Sans Condensed.

**Comment by bagau** [comment]
Exo 2 missing ttf too, but I could download ttf files on google fonts https://fonts.google.com/specimen/Exo+2?selection.family=Exo+2:400,500,600

**Comment by chris-h1** [comment]
Same with Quicksand, missing TTF in download.

**Comment by nikoskip** [comment]
Hi! I created the script you are talking about:

http://nikoskip.me/gfonts.php

I think the issue with TTF fonts is resolved, please take a look.

Cheers!

**Comment by juanpablocs** [comment]
Open Sans ttf not found :( =>https://google-webfonts-helper.herokuapp.com/fonts/open-sans?subsets=cyrillic

**Comment by majodev** [comment]
Fixed in [07907ca](https://github.com/majodev/google-webfonts-helper/commit/07907ca70896d8cc69a99903779c1ebb60ef156b).
