### ISSUE TITLE
How to host Google web fonts helper in wordpress?

### ISSUE THREAD

**Issue by alexlii1971** [majodev/google-webfonts-helper#42]
Hello, 

You really did a great work!  my question is how to host font in Wordpress?

Unfornately, I am not technical background, so how to Host google fonts on our local server? is there  a plugin to do fetch google fonts and save on server automatically?

I am using a theme which provide quick CSS option, I can input the CSS there.

would you please let me know  where or which directory of fold I should upload these fonts I download from your site please?

Thanks.

Alex

**Comment by lorrandavid** [comment]
Hey @alexlii1971,

I don't know if there's a plugin to fetch all the fonts and save on server but you can do it via FTP, just download the fonts and drop them on your `wp-content/themes/YOUR_THEME/fonts`, then reference them in your css just like it shows on `Step 3`. I think it should be easier than install a plugin just for this task.

**Comment by majodev** [comment]
Ahmad wrote an article on that, have not used it personally but it does look promising.

[How to Host Google Fonts Locally in WordPress](https://www.news47ell.com/how-to/host-google-fonts-locally-wordpress/)

Closing as out of scope for this service, but feel free to discuss here.
