### ISSUE TITLE
Rename fonts to be compliant to SIL Open Font License (OFL)

### ISSUE THREAD

**Issue by alex-becker-startp** [majodev/google-webfonts-helper#45]
After reading the [Open Font License FAQ](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#c2f18d38) I understand that a font has to be renamed when downloaded using your tool.
The License requires that the original font name (referred as _Reserved Font Name_) has not to be used when the font was modified (i.e. converted, repacked etc) in any way.

I have no clue how I could do the renaming technically.
Just renaming the files did not work. So I think the name is embedded somewhere within the files, too.

Can you add an option to rename the selected font when building the web font packages?
Or is there an easy (or even doable) way to rename the fonts in the generated derivates later?

Regards, Alexander

**Comment by alex-becker-startp** [comment]
I helped me out renaming each font metadata using FontForge

**Comment by majodev** [comment]
Not sure if this is required as we don't convert / repack them in any way actually, these are the exact same files you would be requesting if you are using the original css from google fonts...

**Comment by majodev** [comment]
stale
