### ISSUE TITLE
Libre Franklin wrong names in url

### ISSUE THREAD

**Issue by foorbie** [majodev/google-webfonts-helper#50]
When you're trying to install the font-family "Libre Fanklin", you'll fail by just copy and paste, because the names in the css-code and the names of the font files are not the same...
one says latin_latin-ext and teh other latin-ext_latin or something like this.

It's easy to fix, but annoying and difficult to find the bug, if you're are uncommon with css and stuff like this.

**Comment by majodev** [comment]
stale
