### ISSUE TITLE
Safari still does not seem to work

### ISSUE THREAD

**Issue by hagenbuch** [majodev/google-webfonts-helper#56]
I followed the instructions and the fonts do work for up to date Chrome, Firefox, Opera browsers on Mac OS X 10.13.4, but not yet on a up-to date Safari, both on a Macbook and an iPad Air 4: I get Times Roman because I did intentionally not specify a "replacement" font. I hope it's OK mentioning the website so you can have a look: www.dellekom.de

This might have to do with issue #21 - if those browsers require woff2 files and those are not being delivered correctly.

**Comment by majodev** [comment]
closed, old.
