### ISSUE TITLE
Lato zip download not possible

### ISSUE THREAD

**Issue by Netti-B** [majodev/google-webfonts-helper#59]
Hello!

Sorry, but I'm unable to download Lato zip file.
Tryed in Chrome, Opera and FF: [Lato](https://google-webfonts-helper.herokuapp.com/api/fonts/lato?download=zip&subsets=latin&variants=300,700,regular,italic,700italic)

Message:
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

Regards,
Jeanette

**Comment by Schwiezer** [comment]
I can confirm the error. Tried on Google Chrome. Seems like all other fonts work fine... except for Lato. Are there any alternative download methods / sources that offer the magnitude of different formats as this site does? We need "Lato" really urgently...

**Comment by majodev** [comment]
hm, this is working fine by now. Looks like there were issues while downloading the actual files from the google's cdn...
