### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by SoftCreatR** [majodev/google-webfonts-helper#68]
I've used this in my fork of this project, however i don't need it anymore. Maybe you want to use it :)

![preview](https://user-images.githubusercontent.com/81188/49703928-c08b6200-fc0b-11e8-8c21-a2b6771e7b9d.png)

SVG: [logo-01-01.zip](https://github.com/majodev/google-webfonts-helper/files/2661090/logo-01-01.zip)

**Comment by majodev** [comment]
Sorry for never responding back. Thanks but I would worry too much about trademark issues using this.
