### ISSUE TITLE
Add `font-display`

### ISSUE THREAD

**Issue by thejimbirch** [majodev/google-webfonts-helper#69]
On Google's [Web Fundamentals - Web Font Optimization page](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#customize_the_text_rendering_delay), they recommend using `font-display`:

`font-display: auto; /* or block, swap, fallback, optional */`

> To ensure consistency moving forward, the CSS Working Group has proposed a new @font-face descriptor, [font-display](https://drafts.csswg.org/css-fonts-4/#font-display-desc), and a corresponding property for controlling how a downloadable font renders before it is loaded.

Thanks for a great tool!

**Comment by konfuzed** [comment]
In fact, even just having the default auto entry (and a linked note about why to use it and how) would go a long way to help teach folks, too. And yes, wonderful tool thank you!

**Comment by SilasReinagel** [comment]
This would be a very nice feature to have!

Can we get this PR merged?

**Comment by JayHoltslander** [comment]
+1

**Comment by vieregg-jfc** [comment]
+1

**Comment by cseas** [comment]
+1 Can someone tag the maintainers here?
