### ISSUE TITLE
Serve full TTFs (available via Fonts Developer API)

### ISSUE THREAD

**Issue by davelab6** [majodev/google-webfonts-helper#7]
The full TTF URLs are available via https://developers.google.com/fonts/docs/developer_api and those TTFs should be used by this service, because those are the ones actually being served to users and offered for download from the GF directory 'download collection' service.

**Comment by majodev** [comment]
Just to clarify, programmatically downloading *complete* archives of a specific font already works.

To download a zip archive that includes all supported subsets/charsets of a specific font id, you'd have to:
1. get the font resource by its id (e.g. GET `/api/fonts/arimo`),
2. parse the `subsets` array of the response JSON body and 
3. append this to the `?subsets` query parameter at the download endpoint (e.g. `/api/fonts/arimo?download=zip&subsets=cyrillic-ext,cyrillic,latin-ext,...`). 

However, you are requesting to simply this workflow by allowing a GET `/api/fonts/arimo?download=zip&subsets=all` call to return a zipped archive with complete font charsets?

**Comment by davelab6** [comment]
I mean that you could use the 'all' subset of the fonts API itself:

```
$ curl "http://fonts.googleapis.com/css?family=Open+Sans";
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Open Sans'), local('OpenSans'), url(http://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3aCWcynf_cDxXwCLxiixG1c.ttf) format('truetype');
}
$ curl "http://fonts.googleapis.com/css?family=Open+Sans&subset=all"
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Open Sans'), local('OpenSans'), url(http://fonts.gstatic.com/s/opensans/v13/IgZJs4-7SA1XX_edsoXWog.ttf) format('truetype');
}
$
```

Also, the full TTF URLs are also available via https://developers.google.com/fonts/docs/developer_api

**Comment by davelab6** [comment]
Where are you fetching the fonts from? github.com/google/fonts.git? :)

**Comment by majodev** [comment]
Hi,

Nope, the link to the font in a specific format gets directly parsed from the CSS which gets requested via specific UAs from `fonts.googleapis.com/css?family={font-family}&subset={font-subset}`. See [here](https://github.com/majodev/google-webfonts-helper/blob/master/server/logic/cssFetcher.js#L78).

It's basically the same technique that Clemens Lang introduced with his bash scripts [here](https://neverpanic.de/blog/2014/03/19/downloading-google-web-fonts-for-local-hosting/).
