### ISSUE TITLE
heroku app returning 503

### ISSUE THREAD

**Issue by jacobg** [majodev/google-webfonts-helper#73]
`https://google-webfonts-helper.herokuapp.com/api/fonts/roboto?subsets=latin`

![Screen Shot 2019-03-10 at 12 09 47 PM](https://user-images.githubusercontent.com/736985/54087810-6b0b4200-432d-11e9-9f67-944c1c397f84.png)

It used to work fine for months via `@beyonk/google-fonts-webpack-plugin`.

But `https://google-webfonts-helper.herokuapp.com/api/fonts` return 200 with json.

**Comment by majodev** [comment]
Hm, seems to work fine currently? I would guess a upstream hickup?

**Comment by jacobg** [comment]
Yes it works fine now. Thanks.
