### ISSUE TITLE
API Error 503 on Noto Sans JP subset=Japanese

### ISSUE THREAD

**Issue by elfwine** [majodev/google-webfonts-helper#74]
https://google-webfonts-helper.herokuapp.com/fonts/noto-sans-jp?subsets=japanese

The above URL returned an API error (503). The default subset 'Latin' works fine though.

**Comment by majodev** [comment]
Hm, restarted. Works, potentially the currently poor-mans caching implementation is insufficient with the current traffic load (designed ephemeral, however dyno is never restarted).
