### ISSUE TITLE
heroku app failing for open sans

### ISSUE THREAD

**Issue by jacobg** [majodev/google-webfonts-helper#81]
Open sans is failing with application error:
https://google-webfonts-helper.herokuapp.com/api/fonts/open-sans?download=zip&subsets=latin&variants=regular&formats=eot,woff2,woff,ttf,svg

![Screen Shot 2019-06-27 at 11 28 58 AM](https://user-images.githubusercontent.com/736985/60279295-c8240700-98ce-11e9-9c68-1e4358054241.png)

But roboto works fine:
https://google-webfonts-helper.herokuapp.com/api/fonts/roboto?download=zip&subsets=latin&variants=regular&formats=eot,woff2,woff,ttf,svg

**Comment by jacobg** [comment]
Maybe would it be a good idea to cache the fonts on the local build machine, so transient errors don't fail builds?

**Comment by fabriziociampini** [comment]
Please fix Open Sans issue, same error here

**Comment by jacobg** [comment]
This is happening again now:
```
40% building 83/114 modules 31 active /Users/j/workspace/f/console/node_modules/core-js/modules/es.regexp.to-string.js(node:29902) UnhandledPromiseRejectionWarning: Error: Service Unavailable
    at /Users/j/workspace/f/console/node_modules/@beyonk/google-fonts-webpack-plugin/src/GoogleWebfonts.js:265:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Going to https://google-webfonts-helper.herokuapp.com/api/fonts also shows the application error page as shown in screenshot above in original comment.

**Comment by jacobg** [comment]
Down again

**Comment by majodev** [comment]
dup https://github.com/majodev/google-webfonts-helper/issues/151#issuecomment-1240398538
