### ISSUE TITLE
 Muli font is broken

### ISSUE THREAD

**Issue by alarstyle** [majodev/google-webfonts-helper#89]
In this repository letter "A" in Muli font looks like this:
![image](https://user-images.githubusercontent.com/1730120/69049776-4eb9bc00-0a09-11ea-9921-8d982373e0f1.png)

**Comment by alarstyle** [comment]
Sorry, was my mistake :)

**Comment by maddesigns** [comment]
@alarstyle What was the problem? I’ve the same issue. :(

**Comment by alarstyle** [comment]
@maddesigns Well, I closed this issue when I understood that I used wrong font files, but later I find out that issue still wasn't fixed even with the correct files. So the only solution for me was to switch to emended styles from google fonts.

**Comment by davelab6** [comment]
This is a known problem with older versions of macOS and the latest version
of the OpenType font format.

**Comment by Mushr0000m** [comment]
I have this exact issue, and I am on MacOS using only the Woff format. Is there a way to fix this ?
