### ISSUE TITLE
Many fonts (e.g. Petit Formal Script and Work Sans) return 503 error.

### ISSUE THREAD

**Issue by Dan0sz** [majodev/google-webfonts-helper#99]
Hi,

Everything seems to work, except for this font. Temporary issues or an actual bug?

**Comment by sunixzs** [comment]
Ahoi. Maybe the same...

After pressing the button `Download files > work-sans-v7-latin.zip` the servers responds with a 503.

Page with the button:  
https://google-webfonts-helper.herokuapp.com/fonts/work-sans?subsets=latin

Links in the button:  
https://google-webfonts-helper.herokuapp.com/api/fonts/work-sans?download=zip&subsets=latin&variants=200,600,regular

**Comment by stevenart** [comment]
Seems like every font is returning a 503 "API ERROR" page right now.
(Google Fonts website is up.)

**Comment by Dan0sz** [comment]
Well, not all. But definitely a lot. I'll change the issue title.

**Comment by scrobbleme** [comment]
Same here

**Comment by leifj** [comment]
same here

**Comment by scrobbleme** [comment]
Seems to be working again. Would be nice to know, what the problem was.

**Comment by stevenart** [comment]
I can confirm it's working again.

I don't know if it's connected by code provided by Google now includes 2 different files for charset (1 for latin and 1 for latin extended) with a new "unicode-range" property in the CSS.

For exemple:
```
@font-face {
  font-family: 'DM Serif Display';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: latin-ext-file.woff2;
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;

@font-face {
  font-family: 'DM Serif Display';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: latin-file.woff2;
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

I don't know if it's that new and if it impacted this project API however. Just something I found.

**Comment by Dan0sz** [comment]
Awesome. Happy :)

I'll close this issue.
